network_adapters:
  expected_names_25:
    - "A - d3Net 1Gbit"
    - "B - Media 10Gbit"
    - "C - Media 10Gbit"
    - "D - 25Gbit"
    - "E - 25Gbit"
    - "disguiseMGMT"
  expected_names_100:
    - "A - d3Net 1Gbit"
    - "B - Media 10Gbit"
    - "C - Media 10Gbit"
    - "D - 100Gbit"
    - "E - 100Gbit"
    - "disguiseMGMT"

audio_devices:
  expected_input_names:
    - "ADAT (1+2) (RME HDSPe AIO)"
    - "ADAT (3+4) (RME HDSPe AIO)"
    - "ADAT (5+6) (RME HDSPe AIO)"
    - "ADAT (7+8) (RME HDSPe AIO)"
    - "AES (1+2) (RME HDSPe AIO)"
    - "Analog (1+2) (RME HDSPe AIO)"
    - "Microphone (2- USB Audio Device"
    - "Microsoft Sound Mapper - Input"
    - "SPDIF (RME HDSPe AIO)"
  expected_output_names:
    - "ADAT (1+2) (RME HDSPe AIO)"
    - "ADAT (3+4) (RME HDSPe AIO)"
    - "ADAT (5+6) (RME HDSPe AIO)"
    - "ADAT (7+8) (RME HDSPe AIO)"
    - "AES (1+2) (RME HDSPe AIO)"
    - "Analog (1+2) (RME HDSPe AIO)"
    - "Microsoft Sound Mapper - Output"
    - "Phones (RME HDSPe AIO)"
    - "SPDIF (RME HDSPe AIO)"
    - "Speakers (2- USB Audio Device)"

media_drives:
  windows_drive_letter: "C:\\"
  windows_volume_name: "Windows"
  media_drive_letter: "D:\\"
  media_volume_name: "Media"

raid_controller:
  hardware_id: "PCI\\VEN_1000&DEV_10E2&SUBSYS_40001000&REV_00"
  device_name: "MegaRAID 9560-16i"
  tool_path: "C:\\Program Files\\LSI\\LSIStorageAuthority\\startupLSAUI.bat"

hardware_info:
  description: ""
  osHardwarePlatform: ""
  hasD3Installed: false
  requiresNotchLicense: false
  usesCaptureCards: false
  validateGPUModelName: ""
  usesHammerfallAudio: false

product_codes:
  - ProductCode: ""
    d3Product: ""
    d3Model: ""

allowed_capture_card_types:
  - ""

adapter_names:
  AdapterNames1G:
    - ""
  AdapterNames10G:
    - ""
  AdapterNames100G:
    - ""

registry_keys:
  oem_information_folder: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\OEMInformation"
  oem_information_entries:
    os_release: "OSRelease"

d3Service_api_endpoints:
  all_d3_servers_os_info: "127.0.0.1/api/service/system/osinfo"

windows_settings:
  windows_allowed_apps:
    - "mspaint"
    # - "SnippingTool"  I cant find the processs name for this. You can start the process with Start-Process SnippingTool.exe, but it is renamed something else
    - "psr"
    - "notepad"
    - "wordpad"
    - "charmap"
    - "mstsc"

  chrome_bookmark_urls:
    - "https://www.disguise.one/"    #This one NEEDS to be the home page
    - "https://help.disguise.one/"
    - "https://download.disguise.one/"

  chrome_home_url:
    - "https://www.disguise.one/"
  
  chrome_allowed_history:
    - "disguise"
    - "codemeter"
    - "testrail"

  taskbar_apps:
    - "File Explorer"
    - "Google Chrome"
  
  start_menu_apps_default:
    win10:
      - "Google Chrome"
      - "d3manager"
      - "Media Player Classic"
      - "Recycle Bin"
    win11:
      - "Google Chrome"
      - "d3manager"
      - "File Explorer"
      - "Recycle Bin"
    DELTACAST:
      - "dCare"
      - "dScope"

devices_settings:
  deltacast_apps:
    - "C:\\Program Files\\Deltacast\\dCARE\\bin\\dCARE"
    - "C:\\Program Files\\Deltacast\\dSCOPE\\bin\\dSCOPE"
  
  matrox_apps:
    - "mveXinfo"

  bluefish_apps:
    - "blueinfo"

  allowed_warning_on_device:
    - ["Microsoft Basic Display Adapter", "Error"]

driver_choco_package_handle_automated_device_manager_version_test_blocklist: #can put choco package handles here or shared package changes (pref shared if it exists)
    - "NVIDIA_Driver"      #This is the SHared external handle which covers both nvidia and nvidia_feature - we dont test for nvidia version through device manager - only nvidia control panel
    - "AMD_Driver"         #This is the SHared external handle which covers  d3_amd_pro, amd_viipro & amd_wx91 - we dont test for AMD version through device manager - only its control panel
    - "deltacast_cert"     #this is just the certificate and not the driver
    - "deltacast_dcare"    #this is just the software so no driver check required
    - "deltacast_dscope"   #this is just the software so no driver check required
    - "bluefish_tools"     #This is the bluefish software not the driver
    - "intel_nvme"         #NVME Driver doesnt show up in device manager as a device
    - "intel_network"      #Intel Network Adapters dont show consistant version numbers in Device Manager - unable to check automatically or even manually
    - "intel_network_x710" #Intel Network Adapters dont show consistant version numbers in Device Manager - unable to check automatically or even manually
    - "Mellanox_NIC_Adapter_Driver" #Shared Extranal Handle for mellanox (covers bot current and deprecated mellanox choco packages) - we dont check driver version in device manager, only the mellanox tools app in installed apps
    - "lsa"                #This is the software install not the driver install for broadcomm - its linked to hardware in CVT but it doesnt show up in Device manager          

driver_choco_package_handle_automated_installed_apps_and_features_version_test_blocklist: #can put choco package handles here or shared package changes (pref shared if it exists)
    - "vcredist140" #This one doesnt show up in installed apps so we skip this check - the other vcredist ones all do at time of writing
    - "Mellanox WinMFT" #This is the SHared external handle, this doesn't appear in installed apps
    - "d3"              #these dont show up as windows apps (ie app store apps) so test will fail if we check these (doesnt matter as we test d3 install as its own seperate test)
    - "d3_testBranch"   #these dont show up as windows apps (ie app store apps) so test will fail if we check these (doesnt matter as we test d3 install as its own seperate test)

approvedStartupApps_RegistryLocations:
    - "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\StartupApproved\\Run"
    - "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\StartupApproved\\StartupFolder"
    - "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\StartupApproved\\Run"
    - "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\StartupApproved\\Run32"

approvedStartupApps_RegistryKeys:
    - "d3buddy"
    - "FirefaceMixTray2"
    - "HDSPTray1"
    - "SecurityHealth"
    - "CodeMeter Control Center*"
    - "WinMFT Cleanup*"
    - "OneDrive"
    - "MicrosoftEdge*"
    - "mveXinfo*"

approvedDisabledApps_RegistryKeys:
    - "MicrosoftEdge*"
    - "mveXinfo*"
    - "OneDrive"
